export const LOGIN_LOGIN_REQUEST = 'LOGIN_LOGIN_REQUEST';
export const LOGIN_LOGIN_SUCCESS = 'LOGIN_LOGIN_SUCCESS';
export const LOGIN_LOGIN_FAIL = 'LOGIN_LOGIN_FAIL';

export const ORDER_GETCODE_REQUEST = 'ORDER_GETCODE_REQUEST';
export const ORDER_GETCODE_SUCCESS = 'ORDER_GETCODE_SUCCESS';
export const ORDER_GETCODE_FAIL = 'ORDER_GETCODE_FAIL';