export const ORDER_SCANCODE_REQUEST = 'ORDER_SCANCODE_REQUEST';
export const ORDER_SCANCODE_SUCCESS = 'ORDER_SCANCODE_SUCCESS';
export const ORDER_SCANCODE_FAIL = 'ORDER_SCANCODE_FAIL';

export const ORDER_PRINT_REQUEST = 'ORDER_SCANCODE_REQUEST';
export const ORDER_PRINT_SUCCESS = 'ORDER_SCANCODE_SUCCESS';
export const ORDER_PRINT_FAIL = 'ORDER_SCANCODE_FAIL';